

services:
  web:
    image: tahaalghutani/docker-test
    
    env_file:
      - .env.prod
    depends_on: 
      - postgres
      - redis
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
