version: "3.8"

services:
  web:
    build:
      context: .
    image: dev-django-app
    volumes:
      - .:/app
    
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
      - POSTGRES_DB=django_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on: 
      - postgres
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - web

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    networks:
      - web

  redis:
    image: redis
    restart: always
    networks:
      - web

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - web

volumes:
  postgresql_data:

  
