

services:
  web:
    
    image: tahaalghutani/docker-test
    expose:
      - "8000"
    

    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on: 
      - postgres
      - redis
    networks:
      - mynet

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: taha_db
      POSTGRES_USER: tahaalghutani
      POSTGRES_PASSWORD: alghutani123
    networks:
      - mynet

  redis:
    image: redis
    restart: always
    networks:
      - mynet

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - web
    networks:
      - mynet

volumes:
  postgresql_data:
networks:
  mynet:


