

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: tahaalghutani/docker-test
    expose:
      - "8000"
    command: >
      sh -c "
        python manage.py migrate &&
        python create_superuser.py &&
        python manage.py runserver 0.0.0.0:8000
      "

    

    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=tahaalghutani
      - DJANGO_SUPERUSER_EMAIL=alghutanitaha@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=Taha2003#
    depends_on: 
      - postgres
      - redis
    networks:
      - mynet

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: taha_db
      POSTGRES_USER: tahaalghutani
      POSTGRES_PASSWORD: alghutani123
    networks:
      - mynet

  redis:
    image: redis:latest
    restart: always
    networks:
      - mynet

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - web
    networks:
      - mynet

volumes:
  postgresql_data:
networks:
  mynet:


