

services:
  web:
    
    image: tahaalghutani/docker-test
    expose:
      - "8000"
    deploy:
      replicas: 6
      
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s

    environment:
      - DEBUG=0
      
      - POSTGRES_DB=django_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on: 
      - postgres
      - redis
    networks:
      - web

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    networks:
      - web

  redis:
    image: redis
    restart: always
    networks:
      - web

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - web
    networks:
      - web

volumes:
  postgresql_data:
networks:
  web:
    driver: bridge

