

services:
  web:
    image: tahaalghutani/docker-test
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    env_file:
      - .env.prod
    depends_on: 
      - postgres
      - redis
    networks:
      - mynet

networks:
  mynet:
    driver: overlay
