

services:
  web:
    build:
      context: .
    image: dev-django-app
    volumes:
      - .:/app
    env_file:
      - .env.dev
    
    
   
    command: >
      sh -c "python wait_for_postgres.py &&
         python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"
networks:
  mynet:
    driver: bridge


   


   



  




